# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yujin2019.github.io/yujin/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yujin Kim
user_description: I am majored in computer education. I want to be a developer
user_title: 판교 꿈나무
email: danjjank@gmail.com
twitter_username: ㅇ에에에ㅔㅇ
github_username:  yujin2019
gplus_username:  이게모야ㅑㅑ

exclude: ['package.json', 'src' , 'node_modules']
