title: Yujin's blog
author: Yujin Kim
email: danjjank@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
    Hi! I am majored in computer education. I'm dreaming now! Keep on watching me ^_^/

show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/about-me"

# Minima date format
url: "https://yujin2019.github.io" 
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 판교꿈나무
  tagline: Student, Developer(someday)
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: uzi__i
    github: yujin2019
    instagram: uzi__i
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed